### ISSUE TITLE
微信问题

### ISSUE THREAD

**Issue by wisfern** [zhuoqianmingyue/springbootexamples#10]
我用自己的微信申请的订阅号，貌似无法跑这里的两个例子，你是申请了服务号，并用企业认证了？

**Comment by zhuoqianmingyue** [comment]
个人订阅号是没有没有开放微信支付接口权限，只是开发一些基础接口权限。您说的例子是那个？

**Comment by zhuoqianmingyue** [comment]
JS-SDK自定义微信分享和获取微信公众号下的用户信息2个例子使用的是微信提供的测试账号。文档中的例子需要在微信后台配置域名信息才可以使用，自己本地调试只能使用测试账号。可以访问：https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Requesting_an_API_Test_Account.html 申请测试账号。
个人订阅号接口权限请查看：
https://developers.weixin.qq.com/doc/offiaccount/Getting_Started/Explanation_of_interface_privileges.html

**Comment by wisfern** [comment]
好的，谢谢。
